# Jekyll Resume Theme

# Site settings
title: Janice Lee
email: janice.lee@pomona.edu 
description: my personal website 
baseurl: ""
url: "jlad2017.github.io"
name: Janice Lee
job: Junior at Pomona College studying Computer Science and Statistics 
location: Claremont, CA 
languages: HTML, CSS and Javascript
# twitter_username: mattcouchman
github_username:  jlad2017
# codepen_username:  mattcouchman
email_address: janice.lee@pomona.edu

# Build settings
markdown: kramdown
