# Jekyll Resume Theme

# Site settings
title: Janice Lee
email: janice.lee@pomona.edu 
description: my personal website 
baseurl: ""
url: "jlad2017.github.io"
name: Janice Lee
job: Junior at Pomona College 
location: Claremont, CA 
languages: Python, Java, C++ 
github_username:  jlad2017
email_address: janice.lee@pomona.edu

# Build settings
markdown: kramdown
